# Generated by Django 4.2.11 on 2024-05-11 01:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('cam_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name_cam', models.CharField(max_length=20)),
                ('coords_cam', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('adresse_cam', models.GenericIPAddressField(blank=True, null=True)),
                ('num_port', models.CharField(blank=True, null=True)),
                ('rest_de_path', models.CharField(blank=True, null=True)),
                ('description_cam', models.TextField(blank=True, null=True)),
                ('custom_url', models.TextField(blank=True, null=True)),
                ('is_full_rtsp_url', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name_client', models.CharField(null=True)),
                ('pseudo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('', '-'), ('M', 'Male'), ('F', 'Femelle'), ('O', 'Organization')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pics/')),
                ('description_client', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('name_project', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ville', models.CharField(null=True)),
                ('contrat_picture', models.ImageField(null=True, upload_to='contract_pics/')),
                ('description_projet', models.TextField(blank=True, null=True)),
                ('pseudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Superviseur.client')),
            ],
        ),
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_superviseur', models.CharField(null=True)),
                ('pseudo', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('', '-'), ('M', 'Male'), ('F', 'Femelle'), ('O', 'Organization')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('description_superviseur', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name_zone', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('coords_polys', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('description_zone', models.TextField(blank=True, null=True)),
                ('name_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Superviseur.projet')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_data', models.JSONField(null=True)),
                ('path_to_image', models.CharField(null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Superviseur.cam')),
            ],
        ),
        migrations.AddField(
            model_name='cam',
            name='name_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Superviseur.projet'),
        ),
    ]
