# Generated by Django 4.2.11 on 2024-05-11 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Superviseur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Superviseur.client'),
        ),
    ]
