# Generated by Django 4.2.11 on 2024-05-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superviseur', '0002_detectionresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pseudo',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projet',
            name='contrat_picture',
            field=models.ImageField(blank=True, null=True, upload_to='contract_pics/'),
        ),
    ]
