# Generated by Django 4.2.11 on 2025-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superviseur', '0003_alter_client_pseudo_alter_projet_contrat_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superviseur',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='superviseur',
            name='pseudo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
